[project]
name = "gee_data_fetcher"
version = "0.1.0"
description = "Add a short description here"
authors = ["Etienne Tack <5456949+etiennetack@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
cmd = "python gee_data_fetcher/main.py"

[dependencies]
python = ">=3.12.1,<3.13"
earthengine-api = ">=0.1.389,<0.2"
pydrive2 = ">=1.19.0,<1.20"
geopandas = ">=0.14.3,<0.15"
pendulum = ">=3.0.0,<3.1"
click = ">=8.1.7,<8.2"
tqdm = ">=4.66.2,<4.67"
shapely = ">=2.0.2,<2.1"
